version: '3'

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://postgres:sql123@db:5432/datapy
    depends_on:
      - db
    command: >
      sh -c "
        while ! nc -z db 5432; do
          echo 'Waiting for database...'
          sleep 1
        done
        python manage.py migrate
        python manage.py runserver 0.0.0.0:8000
      "

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sql123
      POSTGRES_DB: datapy
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
