# Generated by Django 5.1.2 on 2024-10-24 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('necessary', models.BooleanField()),
                ('amount', models.FloatField()),
                ('type_expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.typeexpense')),
            ],
        ),
    ]
