# Generated by Django 5.1.2 on 2024-10-25 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('amount', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
