# Generated by Django 5.0 on 2024-10-25 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_monthlyinput'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlyinput',
            old_name='amount',
            new_name='amountInput',
        ),
    ]
